export  const PATHS = {
  Intro: "Intro",
  Login: "Login",
  Register: "Register",
  Home: "Home",
  ForgetPassword: "ForgetPassword",
  ResetPasswordForm: "ResetPasswordForm",
  AllCategories: "AllCategories",
  CategoryProducts: "CategoryProducts",
  Orders: "Orders",
  OrderDetails: "OrderDetails",
   OffersPage: 'OffersPage',
  UserOptions: "UserOptions",
  AccountDetails: "AccountDetails",
  SavedAdresses: "SavedAdresses",
  ChangePassword: "ChangePassword",
  AllCompaniesScreen:"AllCompaniesScreen",
  CompanyProductsScreen: "CompanyProductsScreen",
  UserOptions: "UserOptions",
};
